// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjnLK-widbWHwej5UTai-5CVp3w8cvcso',
    appId: '1:592018861909:web:d1a700c2794ef3774f09dc',
    messagingSenderId: '592018861909',
    projectId: 'iptc-e6931',
    authDomain: 'iptc-e6931.firebaseapp.com',
    storageBucket: 'iptc-e6931.firebasestorage.app',
    measurementId: 'G-4QZV62R3CX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvwL1o3_wqkFCm-YO7kquvOU19jrdLLlw',
    appId: '1:592018861909:android:356245ccce70afd64f09dc',
    messagingSenderId: '592018861909',
    projectId: 'iptc-e6931',
    storageBucket: 'iptc-e6931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADxY7T_YkaNKmN74d-BjvvYes67sGWAMA',
    appId: '1:592018861909:ios:308f0861895512954f09dc',
    messagingSenderId: '592018861909',
    projectId: 'iptc-e6931',
    storageBucket: 'iptc-e6931.firebasestorage.app',
    iosBundleId: 'com.colombopal.colomboPal',
  );
}
